### PR TITLE
Fix deadlock in advanced subscriber when recovery queries are answered locally.

### LINKED ISSUE #1138: [Bug] Deadlock with local Advanced Subscriber when recovery queries are answered locally
### Describe the bug

A deadlock occurs in Zenoh Pico Advanced Subscriber when a recovery or retransmission query is issued from inside a subscriber callback while holding the subscriber state mutex, and that query is answered locally (same session, AdvancedPublisher cache).

This happens with local subscribers + local queryables and does not require network transport or packet loss to reproduce.

The issue manifests as a thread blocking indefinitely on a mutex already held by the same thread (non-recursive mutex re-entry).

### To reproduce

1. Have an advanced publisher and subscriber within the same session on the same key expression with the following settings:

ze_advanced_publisher_options_t pub_opts;
ze_advanced_publisher_options_default(&pub_opts);
pub_opts.cache.is_enabled = true;
pub_opts.cache.max_samples = 1;
pub_opts.sample_miss_detection.is_enabled = true;

ze_advanced_subscriber_options_t sub_opts;
ze_advanced_subscriber_options_default(&sub_opts);
ze_advanced_subscriber_history_options_default(&sub_opts.history);
ze_advanced_subscriber_recovery_options_default(&sub_opts.recovery);
ze_advanced_subscriber_last_sample_miss_detection_options_default(&sub_opts.recovery.last_sample_miss_detection);

2. Publish a sample.

### System info

- Platform: Ubuntu 24.04
- Zenoh Version: 1.7.2

### PR DESCRIPTION
**Pull request by gmartin82**
Where the `Z_FEATURE_LOCAL_QUERYABLE` feature is enabled, local queries are executed synchronously in the calling thread. In certain code paths, the advanced subscriber initiated queries while holding an internal mutex, causing query callbacks to attempt to re-lock the same mutex, which resulted in a deadlock.

This change fixes the issue by ensuring queries are never invoked while holding the subscriber mutex, and by enforcing correct lock/unlock and rollback semantics when query execution fails. The fix is minimal and scoped to the affected advanced subscriber callbacks.

Fixes #1138.

---
## 🏷️ Label-Based Checklist

Based on the labels applied to this PR, please complete these additional requirements:

**Labels:** `bug`

## 🐛 Bug Fix Requirements

Since this PR is labeled as a **bug fix**, please ensure:

- [x] **Root cause documented** - Explain what caused the bug in the PR description
- [x] **Reproduction test added** - Test that fails on main branch without the fix
- [x] **Test passes with fix** - The reproduction test passes with your changes
- [x] **Regression prevention** - Test will catch if this bug reoccurs in the future
- [x] **Fix is minimal** - Changes are focused only on fixing the bug
- [x] **Related bugs checked** - Verified no similar bugs exist in related code

**Why this matters:** Bugs without tests often reoccur.

**Instructions:**
1. Check off items as you complete them (change `- [ ]` to `- [x]`)
2. The PR checklist CI will verify these are completed

*This checklist updates automatically when labels change, but preserves your checked boxes.*

### CODE REVIEW

File: src/api/advanced_subscriber.c [hunk 1]
```diff
@@ -1070,68 +1100,104 @@ static z_result_t __unsafe_ze_advanced_subscriber_spawn_periodic_query(_ze_advan
...
-            _Z_ERROR("Failed to handle sample in subscriber callback: %i", ret);
+            _Z_ERROR("Failed to prepare query for missing samples");
             return;
         }
 
-        const z_source_info_t *source_info = z_sample_source_info(sample);
-        if (source_info != NULL) {
-            z_entity_global_id_t source_id = z_source_info_id(source_info);
+        z_owned_keyexpr_t query_keyexpr;
+        if (z_keyexpr_clone(&query_keyexpr, z_keyexpr_loan(&state->_query_keyexpr)) != _Z_RES_OK) {
```
Comment (DenisBiryukov91) [inline src/api/advanced_subscriber.c]: do you really need to clone key expression here and in other places given that you are holding an rc copy of state and it will not be dropped until this function returns (which is largely enough to send this ke over the wire) ?

Comment (gmartin82) [reply src/api/advanced_subscriber.c]: I've changed the code to avoid the clone.
