### PR TITLE
Fix ping-pong examples (#226) (#227)

### LINKED ISSUE #226: [Bug] SegFault when running z_ping & z_pong examples
### Describe the bug

In latest ```master``` the z_ping and z_pong examples result in segmentation fault:

```
[1]    54091 segmentation fault  ./z_pong
```

However, this only happens if there is no ```zenohd``` running.

Possible cause: No ```z_check()``` after creating an owned session

### To reproduce

1. Fresh build from the 9b663d5b8aa0e7aa35f0da9285622e0c8cc25649 commit
2. Run ./z_ping or ./z_pong

### System info

System:
* OS: macOS 13.4.1 22F82 arm64
* CPU & GPU: Apple M2

Zenoh:

```
λ › zenohd --version                                                                                                                 ~
[2023-07-04T13:10:59Z INFO  zenohd] zenohd v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
The zenoh router v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
```

### PR DESCRIPTION
**Pull request by cguimaraes**
Fix #226 and #227

### CODE REVIEW

**Comment by cguimaraes** [comment]
@imstevenpmwork can you double check if it fixes both of your issues?

**Comment by imstevenpmwork** [comment]
Hello Carlos, thanks for the quick reply. I tested this PR with the same system and I confirm both of the problems are solved.

File: examples/unix/c11/z_ping.c [hunk 1]
```diff
@@ -79,8 +100,8 @@ int main(int argc, char** argv) {
     _z_mutex_unlock(&mutex);
     z_free(results);
     z_free(data);
-    z_drop(z_move(sub));
-    z_drop(z_move(pub));
```
Comment (p-avital) [inline examples/unix/c11/z_ping.c:83]: z_drop should be favored in c11 examples

File: examples/unix/c11/z_pong.c [hunk 2]
```diff
@@ -19,13 +19,34 @@ int main(int argc, char** argv) {
...
+    if (!z_check(sub)) {
+        printf("Unable to declare subscriber for key expression.\n");
+        return -1;
+    }
+
     while (getchar() != 'q') {
     }
-    z_drop(z_move(sub));
+
+    z_undeclare_subscriber(z_move(sub));
```
Comment (p-avital) [inline examples/unix/c11/z_pong.c:50]: prefer z_drop

File: examples/unix/c99/z_ping.c [hunk 3]
```diff
@@ -78,9 +100,9 @@ int main(int argc, char** argv) {
     _z_mutex_unlock(&mutex);
     z_free(results);
     z_free(data);
-    z_undeclare_subscriber(z_move(sub));
-    z_undeclare_publisher(z_move(pub));
-    z_close(z_move(session));
+    z_undeclare_subscriber(z_subscriber_move(&sub));
```
Comment (p-avital) [inline examples/unix/c99/z_ping.c:103]: don't switch this to z_drop, it's a c99 example (leaving the comment just in case)

File: examples/windows/z_ping.c [hunk 4]
```diff
@@ -77,8 +97,8 @@ int main(int argc, char** argv) {
     _z_mutex_unlock(&mutex);
     z_free(results);
     z_free(data);
-    z_drop(z_move(sub));
-    z_drop(z_move(pub));
+    z_undeclare_publisher(z_move(pub));
```
Comment (p-avital) [inline examples/windows/z_ping.c:100]: prefer z_drop

File: examples/windows/z_pong.c [hunk 5]
```diff
@@ -19,13 +19,34 @@ int main(int argc, char** argv) {
...
+    if (!z_check(sub)) {
+        printf("Unable to declare subscriber for key expression.\n");
+        return -1;
+    }
+
     while (getchar() != 'q') {
     }
-    z_drop(z_move(sub));
+
+    z_undeclare_subscriber(z_move(sub));
```
Comment (p-avital) [inline examples/windows/z_pong.c:50]: prefer z_drop

**Review by p-avital — CHANGES_REQUESTED** [review]

File: examples/unix/c11/z_ping.c (hunk 1 above)
Comment (cguimaraes) [reply examples/unix/c11/z_ping.c:83]: Done!

File: examples/unix/c11/z_pong.c (hunk 2 above)
Comment (cguimaraes) [reply examples/unix/c11/z_pong.c]: Done!

File: examples/unix/c99/z_ping.c (hunk 3 above)
Comment (cguimaraes) [reply examples/unix/c99/z_ping.c]: Done!

File: examples/windows/z_pong.c (hunk 5 above)
Comment (cguimaraes) [reply examples/windows/z_pong.c]: Done!

**Review by p-avital — APPROVED** [review]
