### PR TITLE
Fix matching

### LINKED ISSUE #1054: [Bug] Querier matching status listener do not account for querier 'complete' field
### Describe the bug

Matching status/listener logic uses interests which do not propagate queryable completeness - which means that querier's 'complete' field is ignored. This is different from zenoh-rust behavior where querier's 'complete' field is taken into account by matching status/listener.

### To reproduce

declare incomplete Queryable
declare complete Querier
Querier's matching status matching field will be true.

### System info

Any

### PR DESCRIPTION
**Pull request by DenisBiryukov91**
Fix matching logic to account for completeness of queryable
Move matching listener callbacks into _z_write_filter_callback
Check only exact ke equality in case of aggregated interests instead of intersection.
Resolves #1054 
Depends on https://github.com/eclipse-zenoh/zenoh/pull/2210

### CODE REVIEW

File: tests/api.sh [hunk 1]
```diff
@@ -29,11 +29,9 @@ echo "------------------ Running test $TESTBIN -------------------"
 sleep 5
 
 if [ ! -f zenohd ]; then
-    git clone https://github.com/eclipse-zenoh/zenoh.git zenoh-git
+    git clone https://github.com/DenisBiryukov91/zenoh.git zenoh-git
```
Comment (gmartin82) [inline tests/api.sh]: I guess this will be reverted to eclipse-zenoh before being committed?

File: tests/routed.sh [hunk 2]
```diff
@@ -29,11 +29,9 @@ echo "------------------ Running test $TESTBIN -------------------"
 sleep 5
 
 if [ ! -f zenohd ]; then
-    git clone https://github.com/eclipse-zenoh/zenoh.git zenoh-git
+    git clone https://github.com/DenisBiryukov91/zenoh.git zenoh-git
```
Comment (gmartin82) [inline tests/routed.sh]: I guess this will be reverted to eclipse-zenoh before being committed?

**Review by gmartin82 — APPROVED** [review]
Looks good. I'm assuming the git references will be reverted once the corresponding Zenoh PR is merged.

File: tests/api.sh (hunk 1 above)
Comment (DenisBiryukov91) [reply tests/api.sh]: Yes, I temporary modified the branch to ensure that ci will pass

File: tests/routed.sh (hunk 2 above)
Comment (DenisBiryukov91) [reply tests/routed.sh]: Yes, I temporary modified the branch to ensure that ci will pass
