### PR TITLE
Fix _z_condvar_wait_until and z_task_join/detach

### LINKED ISSUE #1050: [Bug] double free or corruption (out) on z_task_detach
### Describe the bug

z_task_detach failed, because of incorrect task cleanup in _z_task_free

### To reproduce

Run in debug mode
```
        z_owned_task_t thread;

        z_task_init(&thread, NULL, log_read_thread, NULL);
        z_task_detach(z_move(thread));
```

### System info

Linux

### PR DESCRIPTION
**Pull request by DenisBiryukov91**
Fix _z_condvar_wait_until for macOS
Fix z_task_join/detach to not free the task pointer

Fixes #1050

### CODE REVIEW

**Review by gmartin82 — APPROVED** [review]
Looks good. Test failures seem unreleated so just need to be rerun before merging.

File: src/system/common/platform.c [hunk 1]
```diff
@@ -28,14 +28,12 @@ z_result_t z_task_init(z_owned_task_t *task, z_task_attr_t *attr, void *(*fun)(v
 z_result_t z_task_join(z_moved_task_t *task) {
     _z_task_t *ptr = &task->_this._val;
     z_result_t ret = _z_task_join(ptr);
-    _z_task_free(&ptr);
```
Comment (steils) [inline src/system/common/platform.c:31]: Why? And how is that needed to add the unit test?
Won't it add memory leak at least on some platforms?

File: src/system/common/platform.c [hunk 2]
```diff
@@ -28,14 +28,12 @@ z_result_t z_task_init(z_owned_task_t *task, z_task_attr_t *attr, void *(*fun)(v
...
     return ret;
 }
 
 z_result_t z_task_detach(z_moved_task_t *task) {
     _z_task_t *ptr = &task->_this._val;
     z_result_t ret = _z_task_detach(ptr);
-    _z_task_free(&ptr);
```
Comment (steils) [inline src/system/common/platform.c:38]: Same question.

File: src/system/common/platform.c (hunk 1 above)
Comment (DenisBiryukov91) [reply src/system/common/platform.c:31]: It is a bug, we should never assume that owned objects were allocated on heap (and even if they do, it is not our responsibility to free them). The unit test crashes without it. Otherwise this function is not used anywhere inside zenoh-pico.

File: src/system/common/platform.c (hunk 2 above)
Comment (DenisBiryukov91) [reply src/system/common/platform.c:38]: Same response.
