### PR TITLE
Fix/remove qos designated initializers

### LINKED ISSUE #352: remove C++17 incompatible designated initializers from headers [Bug]
When compiling zenoh-pico with C++ compiler the following error appears:
```
 /home/runner/work/zenoh-cpp/zenoh-cpp/build/_deps/zenohpico-src/include/zenoh-pico/protocol/definitions/network.h:66:23: error: C++ designated initializers only available with ‘-std=c++20’ or ‘-std=gnu++20’ [-Werror=pedantic]
   66 |     _z_n_qos_t ret = {._val = (uint8_t)((express << 4) | (nodrop << 3) | priority)};
```

This should be corrected like it was done in this fix:
https://github.com/eclipse-zenoh/zenoh-pico/commit/e76e367c3f9df68cf631872ce970b87f3be8803a

To reproduce the issue build https://github.com/eclipse-zenoh/zenoh-cpp project

### PR DESCRIPTION
**Pull request by DenisBiryukov91**
move qos-related functions from header into .c to hide usage of designated initializers from c++ (closes #352)

### CODE REVIEW

**Review by milyin — CHANGES_REQUESTED** [review]
I think it's better to make the fix in the header, without moving implementation to C, like here https://github.com/eclipse-zenoh/zenoh-pico/commit/e76e367c3f9df68cf631872ce970b87f3be8803a
Moving code to C may affect the performance (additional call instead of inlining)

File: include/zenoh-pico/protocol/definitions/network.h [hunk 1]
```diff
@@ -62,8 +62,9 @@ typedef _z_qos_t _z_n_qos_t;
 
 static inline _z_qos_t _z_n_qos_create(_Bool express, z_congestion_control_t congestion_control,
                                        z_priority_t priority) {
+    _z_n_qos_t ret;
     _Bool nodrop = congestion_control == Z_CONGESTION_CONTROL_DROP ? 0 : 1;
-    _z_n_qos_t ret = {._val = (uint8_t)((express << 4) | (nodrop << 3) | priority)};
+    ret._val = (uint8_t)((express << 4) | (nodrop << 3) | priority);
```
Comment (milyin) [inline include/zenoh-pico/protocol/definitions/network.h:67]: I'd prefer the form 
```
_z_n_qos_t ret = { uint8_t)((express << 4) | (nodrop << 3) | priority };
```
This would guarantee that all fields in `_z_n_qos_t` are set.
Though this variant works too.

**Review by milyin — APPROVED** [review]
